apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
data:
  goty-tls-key: echo -n "GOTY_KEY"|base64
  goty-tls-crt: echo -n "GOTY_CRT"|base64