apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
data:
  goty-tls-crt: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
QVNDQktrd2dnU2xBZ0VBQW9JQkFRQ3prQ2IzZmV6M2drN2kKTnpFMmZyQlZhMjk4anV5VFNqVWha
MHM5R2U2UWtQQlNjODlmY05BUTQzMnU2Tkt2RHlSUTFFbEVmanh3czFZbApIUmxwVlN3bjYzTHpZ
SGhBczQzMnpFRHdQZmFYWmt0eU5PbUwxYU5vNG1raVZPTUszU3N2aWxTSmQ2N2V6NjUyCmU3dWo4
QTJTeFFEL1o3L21CZmhtNXVQM1J2ZTY3R1ZucVRQOExjZllFRStMWGJiZGw0S2ZMTk1qNG9IdzdV
K0sKYlZLQU1FbE5WSnJHeHIxSm4zR3Nzb2N1WVpYSkxhVC9HdlZIODNsOCthM25BemtMaEdzMHVI
aHpmU3VYZkZWdAppQnZ2cFVLck4yd2VKbDZtbFJnZmNkcmJudU8zQUk0ZXY2VVQ0MFVVYjlxYy9N
OWYzamFVZHd6ejFiV05VNzQ0CktnRHVJM050QWdNQkFBRUNnZ0VBT2U2UUk5a2swdFhmeld3eEhI
dlRPRHZwUkM1NGRTekQ1M3NEOHpxaWxWR3QKdDJ4VncxMEtRK2loYkFVQnRDa1dkbDJISmVuMFpn
ZjJDeE5RVjRON000WHJHRXBQZ2RCc1JPdXhKOUZWOVpLegpWSzF0akFmcEtMV2paY2d0V0J2ekN1
dCtTcnVxVjRoNXFSQlNnWm01UjFqMzhXN3ZvcTdhYlppZ2crOEpqZXljCklQSzBLckhmb3RxSWlB
eWllbjZ5NjByOUZEL3NhTTd1K0J1eEh5NmpYN0swRmppVkdRVmtISzV6aFFiWm5OWVUKOERITkI0
cjBUajZmWWxwT3FvNkRnTHBPeHAzekpNeTJNR1F0SllBZzJaR0VpbUlMdUVJUWFILzcvZWZTNG52
ZgpZREd2Tlp4bFdYMHA1SWNYOFlmRzJZdDZrRzZlaVRoQ0FDZmdaSkZQb1FLQmdRRG9RVlRUa0NQ
VzNLSXEra3FOCmk0VHUzSjdoNHJNaHRXWDdvV0prQ2VPbHlKSlNsZlgyNHZ4enNCWjZCYlF4ZUo1
S3hvcjJNV041bkg2RGg0L0QKQzdEcE00YjlQeW9kZVg3WXQ1NEJ0QXpHdlZ0ZHlqV1Z0VVBRLzQv
M0UxWnkwQzZqUERlaEp3MWRxYmc4V3dndwpmOFg4M2NTN2hNZHZuSE9hSWFsTE5UdVROd0tCZ1FE
RjY3NWdRb0tBMjdzYThrSmw5eHRzTjVZUytKT2VIZklxCnFPT3dQbEZCenEram5XOTgzWFFNeC92
WDJBKzRpYlg2V2N6MGF0U2dXOWhHdmF6S0hJZmlTdFZHNDVWSkt4Rm4KYjhKcmVrdjhKcGMyTDlR
NysrYnErdUNUZ3VLaHlhNG5YM2VuUFM5Mm1kdURIZENoclQ4b2piSmRmbkV0Ni9OSAp1aXc5Mm1Z
SWV3S0JnUUROakd4WFpMempQcGJqTkdwZ3hQYWNNM01GOVEyV0txV2NRbU1DcUdIcDZnM2R1MHhZ
CitPQjJQb1JWNzlCZTdDSWppWDJZajNNN1FNNFMrQm02aEJGSkFrcFl2TnM0Qkx2SGJ4SU83ZHRV
MUdjVkpZMncKOWlDVHltb09QL1lGWE11NXVlUjk0a01JL3RqSHljVUFyMFI1RzRndWNUL1VQb0Z0
Q3BkNnNSME5sd0tCZ1FDRgpBWm9jZ2xYRlZ1VDBoTjJPUEhQWFU3dXM0QlFEN0VmejF5KzhId1Rv
WG9lMlFuVEx5dDdVUUFqRTB0UXR4WTNmCndqMXorOThNTE95NURYcHpFSjFZdThWOE1ERUF6TXFU
WW8yYlFNS1Ruek43SE1WWjBqMHFxSklIVDZ3UjRjRUIKZ0t5ZVhRWHFoQmI2bEN6Q21mU1p3aStk
bVAxaVNQQml3WUE5eU9sTXhRS0JnUUN5ZXhTK1FMb1ZnazRtR0lSWQpiWTFCclNjMS9XVDFYS21V
MVVMVXJqMkU1VkNCajFJR1pPdXV4aUh6OExoMHlydkViT05lS2VIRlJ4VGFOT3h4CkNabzBVL2FN
Si9HNjRIUE1pR1NCMTlEQXBJa29WbjlXRXJOYnhYWXAvK08xUi9tak05L01PN3lDMm43aTM0aHIK
Ukp1aU5sbEIrUVF1eWpvNWl1RTQvWW5yWlE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==

  goty-tls-key: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lVRUNaNkptczMx
TFFoaGd5QzhGdnlwWHdDRWY4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNR
MHd3SGhjTk1qTXdOREkyTWpBek9UVTBXaGNOTWpRd05ESTFNakF6T1RVMApXakFOTVFzd0NRWURW
UVFHRXdKRFREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFMT1FK
dmQ5N1BlQ1R1STNNVForc0ZWcmIzeU83Sk5LTlNGblN6MFo3cENROEZKenoxOXcwQkRqZmE3bzBx
OFAKSkZEVVNVUitQSEN6VmlVZEdXbFZMQ2ZyY3ZOZ2VFQ3pqZmJNUVBBOTlwZG1TM0kwNll2Vm8y
amlhU0pVNHdyZApLeStLVklsM3J0N1Byblo3dTZQd0RaTEZBUDluditZRitHYm00L2RHOTdyc1pX
ZXBNL3d0eDlnUVQ0dGR0dDJYCmdwOHMweVBpZ2ZEdFQ0cHRVb0F3U1UxVW1zYkd2VW1mY2F5eWh5
NWhsY2t0cFA4YTlVZnplWHo1cmVjRE9RdUUKYXpTNGVITjlLNWQ4VlcySUcrK2xRcXMzYkI0bVhx
YVZHQjl4MnR1ZTQ3Y0FqaDYvcFJQalJSUnYycHo4ejEvZQpOcFIzRFBQVnRZMVR2amdxQU80amMy
MENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGUGFOQVhORjZjNUxFSmhECkQ3N1BidXU1b3U1ck1C
OEdBMVVkSXdRWU1CYUFGUGFOQVhORjZjNUxFSmhERDc3UGJ1dTVvdTVyTUE4R0ExVWQKRXdFQi93
UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIUjk4VEUvWFpSMmVyWEk1MDdxSHZI
KwplbGJGRFdpbUJKVEE4clRRZXlXdWJocVllemlVWm14Q1FIbWZGUVgyUVFjZWRkb2F2U0pyT28x
ZG1Uc1RESDBSCkxDZzBSQ1c4bm5hUHlsREV5bEJFRE5aME42cjQraEFIQ0E1cm9zMlUrV1Zxc2Mr
RFN3SWNSd0syTFYra1pMdDAKTm05STc2eUJzUi9va1ZyUHg2UDljbEJmWU04VHgxa2htQkhKQWJS
djQwaStjRFB4SExPNVB4Y1EvTFVwTXU0SAp0SDRoUmtXQnhOWXdzVEZZNlhSeG1IQUg4SXEwTjF1
TSs2aGlHODZYdEFjckVGcGw0YUNtbXU4b0NJdG1QY2RGCklidEtSYnluM0R5YVJyUUpVRzJnbENa
MzRFWERueFA4cFFSaWk0cWhacHlEZWNxTkhLVGF4a3YzY3pKMkN6bz0KLS0tLS1FTkQgQ0VSVElG
SUNBVEUtLS0tLQo=
