apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
data:
  goty-tls-key: {{ .Env.GOTY_KEY | base64 }}
  goty-tls-crt: {{ .Env.GOTY_CRT | base64 }}