apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
data:
  goty-tls-key: {{ lookup('env', 'GOTY_KEY')}}
  goty-tls-crt: {{ lookup('env', 'GOTY_CRT')}}