apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
stringData:
  tls.key: ${{secrets.GOTY_TLS_KEY}}
  tls.crt: ${{secrets.GOTY_TLS_CRT}}