apiVersion: v1
kind: Secret
metadata:
  name: goty-tls-secret
  namespace: mi-goty-namespace
type: kubernetes.io/tls
data:
  goty-tls-crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lVQ0ZPcmR2NGs5
dVFzeWExY0hJUEFNd0duVlZVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUJoTUNR
MHd3SGhjTk1qTXdOREkyTVRrMU9UTTJXaGNOTWpRd05ESTFNVGsxT1RNMgpXakFOTVFzd0NRWURW
UVFHRXdKRFREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFOTTh6
MXJZcTUwYVlwYkhaSjVEeTRqOVNtVHBhQW5vYkR3czQyZ0orNVZBRGFpYWNndUZ4cE1lNmdJQ3V4
M3oKemFnUjQ1Wkw0N1doZVdMa2hPS2oxbzJnU1Z3bGJUdnFlS21LdzZUUC8wY2xocTlLN1M2Z2Rn
OS93UUEzUHFOYQpQUnZpM0hQVEdkLzJ0ZTh5N1JSN08xNEpUVERhWjdxSWJocFVaM0JFaVJUcE9h
V1VNZlpVYk5CVzNoajAvTitmCkZOd2pDdTBEM2thaHFpTk1sSmMyRC8yRHdEbFVqQzNNbkFvWDBG
MEVlajZOVDhBMWdTL3l1TGZ2TjI5aVkrSlEKVHlVUkE4bUl5bnhLMFY3dDRlKzUxanBFSGFhVnk5
ZGFuOWhCVmkzRVJvcEk5bS9qcXJCQllJeDZmQ2pabm8vTQpxQ3ZPbjlVc3BlVjY0YUN4Y0dRUi9k
Y0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGRFRDK3NTYVRzQzBmTGpVCkRJRk9vZ2IzeG9aNE1C
OEdBMVVkSXdRWU1CYUFGRFRDK3NTYVRzQzBmTGpVRElGT29nYjN4b1o0TUE4R0ExVWQKRXdFQi93
UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHZCttazlwTUVuTFB0QmZ0MTgxVm51
YQpKRTJMQjlNVEg2OWNFWHpVTy83ajB6YjNMNVNVM282SzJKZUdTNXAwMDVJSlJPV3VZM1ZsTDhu
WnRlQ2gyb3VhCnRQeDBqVFRsNFNxd1haMnlDbzU0Ty9TenZQNW5MYWx3anZaQ0VCdEY4VzdDWDB0
eERaek1uRVVmbUVaM2t5S2EKVkp1MnNhUXdyNXhMZ092elM2STArRUozWk5ER0hyeGZ4K2UvREpR
dUFJMWpJRTFQWCtJcDhDTnp2dG5wWCtpYQorZk5EbHNVNlFGYjdZMy9MSC9CWkliQnVKcTlqUVh0
bThxeVhPQU9YMXN4RllLRC82NkZkeitYbldYWDJ4ZXAzCkswdmJKZFd4OW5IekJyZ3VGNFpDR1U5
ZmFCeHRORDFvM1AzT0M5ZFk5NDFCTzIrclZEQmlOTUxSNUxEWCtuST0KLS0tLS1FTkQgQ0VSVElG
SUNBVEUtLS0tLQo=
  goty-tls-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
QVNDQktrd2dnU2xBZ0VBQW9JQkFRRFRQTTlhMkt1ZEdtS1cKeDJTZVE4dUkvVXBrNldnSjZHdzhM
T05vQ2Z1VlFBMm9tbklMaGNhVEh1b0NBcnNkODgyb0VlT1dTK08xb1hsaQo1SVRpbzlhTm9FbGNK
VzA3Nm5pcGlzT2t6LzlISllhdlN1MHVvSFlQZjhFQU56NmpXajBiNHR4ejB4bmY5clh2Ck11MFVl
enRlQ1UwdzJtZTZpRzRhVkdkd1JJa1U2VG1sbERIMlZHelFWdDRZOVB6Zm54VGNJd3J0QTk1R29h
b2oKVEpTWE5nLzlnOEE1Vkl3dHpKd0tGOUJkQkhvK2pVL0FOWUV2OHJpMzd6ZHZZbVBpVUU4bEVR
UEppTXA4U3RGZQo3ZUh2dWRZNlJCMm1sY3ZYV3AvWVFWWXR4RWFLU1BadjQ2cXdRV0NNZW53bzJa
NlB6S2dyenAvVkxLWGxldUdnCnNYQmtFZjNYQWdNQkFBRUNnZ0VCQUp6UzVhS3RmMk1vWm85SVF4
UVlndkFXRS9ndExMZEdYYXlqS3NWZnUrN0gKV2h5VlpSdlcybUQ1TDRRRW9RU1FyMXNheE5zZFJs
WGZKcTVidDZoSE9JOTJzMS84elVjUlFUbWxzckFXVjVCcgpkTDJKSStOYzc2bDhFRDVueFZJak9Z
RU5nTnRnbXpJaUNGb29kY2loNEtaa3czRUVoTVFBYTdXU2VpVG9UTmsvCkgrUXBGTG9oQmxtdm12
a1IyS0ZCSzZ2QW1lVDRUakp3aW9nK29WejJuS09ENlUvV2Y4c0h1RWdQZjg5T0dYakEKdFZFSlhZ
TEFydXp2bTBmZjBzd2JpNjJJUkV2dU85NFlIZWE0M1dTbUJTMnBWVjhQS3NTUHhSMDlEWWorSDVy
TApWdnBaeDJFRnZ1TE9ic2dWcmdxRld1c2JERWp1T3dGMUNORHBGMmpReTdFQ2dZRUE2MEVBV0lY
cVZsSnFCamVKCllFajNwaFYveEIrc0lwcTN4SkNpbDFuemo1RkE5c2cyNEZ6eGRaNXFyMHljbEk2
cm13M0FCRk5lQXQzMnpDRnAKU3l1K1B2akoxc0dubCtkbFJhMlZPOE83RHljWkt0WmcxWXJDZHcz
Y2VHSWNUaWpmMFI4RDVKb25jYWJybVVJRgpaSi9XQi9mVUI1TkpNRmJtLytNc2g4MFJWZThDZ1lF
QTVkMmY0MnROTHdpQTg3aVdKeHZBT2JnUk1ubExQRzdrClNjSkpDcytaVnhKaXZiaHhPSlNHUzdC
d3dQUGcxd3piZUhiaVhmaDE4LzlZZFBKS1RLNkV3MTFhU0F3M3VDWTAKWG1iOTB1bksyNU5UVjFQ
ZVk4UlJXZTdzaVVqVnlqQ2U3TlJuTzhHZ2J5NDVPYmJiYnhmMW9RbUdFM1RTbmd2TgpUMTFjSHBR
MmZwa0NnWUVBaldubWJsQVpmRWhRS1dxSzd0RU41TTA1bjBnMnJocDQ2dlRTZDg1L2hVYVlXWUFp
CjFKMnFHN3pkZm9DOEF1VDhMTm1JR2xHT3lvUm96VzRzSUI2c1hxZ29sQ3FXdHM1RzV5cWY4V3dI
N3VUZTBReEsKNnpKZEVUbkkxS2lOUVVKNnYvYzMzTnY1WiswaDVGOTJaSFZjTUMvK1NZdDB6RlVB
eU1MalNzS3ZjQXNDZ1lFQQp2NGF3Q0QrSnFoeTl4VlVSMXpncUxHMlA5cXhWNGQ3TDNDRkQxdnd1
MmZ2NXhmWitjQlJnNllQMER2R2xiOG5JCnZGRGlRRVlia2RnNmpnYXJuY1R6M2d4VWd4K2E5WmJ2
bjVEVkFQM0lCcmgwZ3BqZy9lTy9uTjJVdkxheFc2eXoKWHNXRDFxaDQwdXFDeC9IeVdGaHdVMk9x
RVdBUGRaeUR6eE1OQkhXZUNsRUNnWUFBdldyY2JQdzJFT2krTFc3SgpCWDJYSTh5Q1REUHB0WmdC
MWNDelpaVTBIS3lFNU15a2FTWTJEMkM0WmhzeEpCakdvRytLY0xjRU5nVTVsK0I0Cm0rZzNtbEJD
T0ZFZTQ2ZjEvME05ckViMDdpYlNLa0VPNTVZV3M2NTl0WFhPVlpjSGxNajdMS2tCK24xN0s2UnUK
S2QzODlMc2dtUHc5cHJXOWVJUlEzcnVKcmc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
