name: Construir, Subir a Docker Hub y Desplegar

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2
      
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Construir y Subir imagen a Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  gastonlc/angularapp:1.0.0-Actions
        file: Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Kubectl
      run: |
        kubectl config set-cluster ModeloDevops-AKS-Reader --server=https://modelodevops-aks-dns-b137e13a.hcp.westeurope.azmk8s.io
        kubectl config set-context ModeloDevops-AKS-Reader --cluster=ModeloDevops-AKS-Reader --namespace=mi-goty-namespace
        kubectl config set clusters.ModeloDevops-AKS-Reader.certificate-authority-data ${{ secrets.KUBECTL_CA }}
        kubectl config set-credentials gaston --token=${{ secrets.KUBECTL_TOKEN }}
        kubectl config set-context ModeloDevops-AKS-Reader --user=gaston
        kubectl config use-context ModeloDevops-AKS-Reader
        kubectl delete secret goty-tls-secret -n mi-goty-namespace
        kubectl apply -k kustomize