name: Construir, Subir a Docker Hub y Desplegar

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    
    - uses: actions/cache@v3
      id: npm-cache      
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.0'

    # - name: Modificar archivo package.json
    #   run: |
    #     echo '{"dependencies": {"@angular/common": "14.2.12"}}' > package.json
  
    - name: Instalar dependencias
      run: |
        npm install --legacy-peer-deps
        npm run build

    # - name: Construir la aplicación Angular
    #   run: ng build

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Subir imagen a Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  gastonlc/angularapp:1.0.0-Actions

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # - name: Configurar Kubectl
    #   uses: azure/k8s-set-context@v1
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Configurar Kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        kubectl config use-context ModeloDevops-AKS-Reader --kubeconfig=kubeconfig.yaml

    - name: Desplegar en Kubernetes
      run: |
        kubectl apply -k ./kustomize --kubeconfig=kubeconfig.yaml
