name: Construir, Subir a Docker Hub y Desplegar

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    
    - uses: actions/cache@v3
      id: npm-cache      
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.0'

    - name: Instalar dependencias y construir
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Subir imagen a Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  gastonlc/angularapp:1.0.0-Actions

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Kubectl
      run: |
        kubectl config set-cluster ModeloDevops-AKS-Reader --server=https://modelodevops-aks-dns-b137e13a.hcp.westeurope.azmk8s.io
        kubectl config set-context ModeloDevops-AKS-Reader --cluster=ModeloDevops-AKS-Reader --namespace=mi-goty-namespace
        kubectl config set-credentials gaston --token=${{ secrets.KUBECTL_TOKEN }}
        kubectl config set-context ModeloDevops-AKS-Reader --user=gaston
        kubectl config use-context ModeloDevops-AKS-Reader
        kubectl config set clusters.ModeloDevops-AKS-Reader.certificate-authority-data ${{ secrets.KUBECTL_CA }}
        kubectl config get-contexts
        kubectl config current-context
        echo "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltOVFMV3g2TFVSU2NVTjBZblJ6YzJ0R1VVVTFSRVpIT1doUWNYVllNSGgzUW1wdVQzZG1OWFk1UlZFaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbWRoYzNSdmJpMTBiMnRsYmkxamNEaDJkeUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG01aGJXVWlPaUpuWVhOMGIyNGlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSmtNVE5qTlRsbU9DMHlOV1l6TFRSbU5qTXRZVEV3T1MweU1EWmpaamd3WkRBMll6UWlMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2WkdWbVlYVnNkRHBuWVhOMGIyNGlmUS5GaFU5NHpjZ05XR0VSUERUc1Frc0V5RlBfbUNDQ3dtSG5COTJUaXU0N21ra09uelVLbFpLVjE4RzVtc0g5TzNxelc1c2t3dE5kTW1DckFqb2xORXZ0cU5nOW5kYUdSb2pYM05GZlYzYlYyVjNkNjdsY0xEZ1pkSmQzMEhja2pKbHNhTEcwZGRUWmdfbnpDRHE0ZmpmRWNoQ1VFeGdGeWJ3aFNJVnpGOThxbXJYdzEtdFgzbjZHZnNlRnlFeV9VRk9hcjY2T0wyNGtHdVl4SmFob01KVDZ1Mzl6dGU2Zmk0OG50VG4za2FOb1RzZF9GUFZoa214d2MxWVdvV2E4X0tTV0tyUWNGWGJmQUVjSEVrYkF4eGNpMFBFUXVVdnZDdlUzWEctcTI3UUtXeFJFLVY2T0tFZlZDWk05bjQ5bldaMXFzRnJSeEZQbWFWdHpCVnE0THVnazFtelViazhMQ04zemVoRS02NlhVTUN4eG9ka1NRYWh3aGxiNGRyMmlEQ054RmdnTUFyTEtrOWlWX1VMUmxQeWk3eUtHazN1d0owU1NaUjl0WlVCTkRhNXR2eFI0emtwVVI2U0p5dU9VZnJhN0V3bk5xaXdyTkN4TmpzUUFwbDJhZV9JOHJHYXl2MVMzYlVaci0zOUhjbklPaWVOeUZna1lza2Jpb0JEZk1QZ3RTVnZNVGwzLXBiQndHa3dYYVI3akcxNzVVT0JWQVBWVFVGeGVxNG5yWWNkRTJaT21VRXlyWFI5ZC1tVWhSbTJOQlF2SmVkSWxZNlRvT1BDQnZSNm9tc19mUEUyS0Qzc3NMY2paakNXT2Mya1Jtd0U4LVJTTXFIYWRxRFZ4aDFIOEFZNkFqZDZSUGYyS3NydTBiLUhFeDY1cXF4WVB4U0FyZWJldW8wTVlYOA==" | base64 -d w0
        kubectl apply -k ./kustomize
          
    # - name: Log y Desplegar en Kubernetes
    #   run: |
    #     az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
    #     az aks get-credentials --resource-group SOCIUSRGLAB-RG-MODELODEVOPS-AKS --name ModeloDevOps-AKS