name: Construir, Subir a Docker Hub y Desplegar

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.0'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node

    - name: Modificar archivo package.json
      run: |
        echo '{"dependencies": {"@angular/common": "14.2.12"}}' > package.json
  
    - name: Instalar dependencias
      run: |
        npm install --legacy-peer-deps
        npm run-script build

    # - name: Construir la aplicación Angular
    #   run: ng build

    - name: Subir imagen a Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  gastonlc/angularapp:1.0.0-Actions

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Configurar Kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Desplegar en Kubernetes
      run: |
        kubectl apply -f deployment.yaml
